#!/usr/bin/env python3
"""
sria_rt_v051_deployment_output_separation.py

SRIA RT v0.5.1 - Deployment-Style Output Separation

Purpose:
- Apply an exported learned SRIA RT ranker to accepted episode JSONL.
- Produce clean deployment-facing analyst queues with no redteam/label fields.
- Optionally produce research/debug queues with validation fields preserved.
- Preserve SRIA explanation metadata while separating it from validation artifacts.

This script does NOT rescan auth.txt and does NOT train a model.
It only loads an existing model artifact generated by prior SRIA RT comparison/export scripts.

Typical use from F:\SRIA\SRIA_RT_v01:

  py sria_rt_v051_deployment_output_separation.py ^
    --accepted-jsonl v036_batches\episodes_v036_accepted.jsonl ^
    --model-artifact v050_train_v033_score_v036\model_v033_rf_depth10_cw_none.joblib ^
    --out-dir v051_deployment_rf_depth10 ^
    --queue-sizes 100,500,1000,5000 ^
    --write-research-debug ^
    --matches-jsonl v036_batches\redteam_matches_v036_FINAL_SPARSE.jsonl

Deployment outputs intentionally exclude:
- label
- redteam_count
- redteam_indices
- exact_start_count
- redteam_group
- any direct validation-only fields

Research/debug outputs may include those fields when --write-research-debug is supplied.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

try:
    import joblib
    import numpy as np
except Exception as e:
    print("ERROR: This script requires numpy and joblib.")
    print("Install with:")
    print("  py -m pip install numpy joblib")
    print(f"Original import error: {e}")
    raise SystemExit(2)


DEFAULT_SIGNAL_NAMES = [
    "first_time_source_user_to_dest",
    "first_time_user_to_dest",
    "first_time_source_to_dest",
    "source_fanout",
    "source_user_fanout",
    "user_fanout",
    "compact_lateral_burst",
    "fanout_velocity",
    "propagation_convergence_bonus",
    "compact_rescue_bonus",
    "source_user_fanout_rescue_bonus",
    "entropy_low_novelty",
    "entropy_soft_duration",
    "entropy_long_duration",
    "entropy_many_events",
    "entropy_extreme_events",
    "entropy_oversized_fanout",
    "entropy_excessive_destinations",
]

VALIDATION_FIELD_NAMES = {
    "label",
    "redteam_count",
    "redteam_indices",
    "exact_start_count",
    "redteam_group",
    "matched_redteam",
    "redteam_event_count",
    "redteam_index",
    "redteam",
    "delta_start",
    "delta_end",
    "exact_start_match",
    "redteam_in_observed_time_range",
}

DEPLOYMENT_CSV_FIELDS = [
    "rank",
    "sria_rt_model_score",
    "severity",
    "review_priority",
    "episode_id",
    "start_time",
    "end_time",
    "duration",
    "source",
    "user",
    "destination_count",
    "events_count",
    "user_count",
    "candidate_gate",
    "legacy_sria_score",
    "legacy_raw_score",
    "novelty_ratio",
    "compactness_score",
    "fanout_velocity_score",
    "peak_velocity_new_dests",
    "first_time_signal_hits",
    "first_time_event_count",
    "new_destination_event_count",
    "explanation_short",
    "signals",
]

RESEARCH_EXTRA_FIELDS = [
    "label",
    "redteam_count",
    "exact_start_count",
    "redteam_indices",
]


def safe_float(v: Any, default: float = 0.0) -> float:
    if v is None:
        return default
    try:
        x = float(v)
        if math.isnan(x) or math.isinf(x):
            return default
        return x
    except Exception:
        return default


def safe_int(v: Any, default: int = 0) -> int:
    if v is None:
        return default
    try:
        return int(float(v))
    except Exception:
        return default


def load_jsonl(path: Path) -> Iterable[Dict[str, Any]]:
    with path.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            if isinstance(obj, dict):
                yield obj


def normalize_signals(signals: Any) -> List[str]:
    if signals is None:
        return []
    if isinstance(signals, list):
        return [str(s) for s in signals if str(s)]
    if isinstance(signals, set):
        return [str(s) for s in signals if str(s)]
    if isinstance(signals, tuple):
        return [str(s) for s in signals if str(s)]
    if isinstance(signals, str):
        if ";" in signals:
            return [s.strip() for s in signals.split(";") if s.strip()]
        if "," in signals:
            return [s.strip() for s in signals.split(",") if s.strip()]
        return [signals] if signals else []
    return []


def episode_id_from_obj(obj: Dict[str, Any]) -> str:
    for k in ("episode_id", "id"):
        if k in obj and obj[k] is not None:
            return str(obj[k])
    ep = obj.get("episode")
    if isinstance(ep, dict):
        for k in ("episode_id", "id"):
            if k in ep and ep[k] is not None:
                return str(ep[k])
    return ""


def load_match_maps(path: Optional[Path]) -> Tuple[Dict[str, List[Dict[str, Any]]], Dict[str, List[int]], Dict[str, int]]:
    by_ep: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    rt_indices_by_ep: Dict[str, List[int]] = defaultdict(list)
    exact_by_ep: Dict[str, int] = defaultdict(int)

    if path is None or not path.exists():
        return by_ep, rt_indices_by_ep, exact_by_ep

    count = 0
    for obj in load_jsonl(path):
        count += 1
        ep = obj.get("episode", {})
        ep_id = str(ep.get("id") or ep.get("episode_id") or obj.get("episode_id") or "")
        if not ep_id:
            continue
        by_ep[ep_id].append(obj)
        idx = obj.get("redteam_index")
        if idx is not None:
            try:
                rt_indices_by_ep[ep_id].append(int(idx))
            except Exception:
                pass
        if obj.get("exact_start_match"):
            exact_by_ep[ep_id] += 1

    unique_pos = len(by_ep)
    unique_rt = len({i for vals in rt_indices_by_ep.values() for i in vals})
    print(f"Loaded {count:,} match records from {path}; positive episodes={unique_pos:,}; represented redteam events={unique_rt:,}")
    return by_ep, rt_indices_by_ep, exact_by_ep


def row_from_episode(
    obj: Dict[str, Any],
    match_by_ep: Dict[str, List[Dict[str, Any]]],
    rt_by_ep: Dict[str, List[int]],
    exact_by_ep: Dict[str, int],
    signal_names: Sequence[str],
) -> Dict[str, Any]:
    ep = obj.get("episode", obj)
    if not isinstance(ep, dict):
        ep = obj

    ep_id = str(ep.get("id") or ep.get("episode_id") or obj.get("episode_id") or "")
    signals = normalize_signals(ep.get("signals"))
    sigset = set(signals)

    start_time = safe_int(ep.get("start_time"))
    end_time = safe_int(ep.get("end_time"))
    duration = safe_float(ep.get("duration"), max(0, end_time - start_time))

    dest_count = safe_float(ep.get("destination_count"), 0.0)
    if dest_count == 0.0:
        dests = ep.get("destinations") or ep.get("destinations_sample") or []
        if isinstance(dests, (list, set, tuple)):
            dest_count = float(len(dests))

    events_count = safe_float(ep.get("events_count"), 0.0)
    new_dest_count = safe_float(ep.get("new_destination_event_count"), dest_count)
    first_time_event_count = safe_float(ep.get("first_time_event_count"), 0.0)

    first_time_signal_hits = safe_float(ep.get("first_time_signal_hits"), 0.0)
    if first_time_signal_hits == 0.0:
        first_time_signal_hits = float(sum(1 for s in signals if s.startswith("first_time")))

    novelty_ratio = safe_float(ep.get("novelty_ratio"), 0.0)
    if novelty_ratio == 0.0 and events_count > 0:
        novelty_ratio = min(1.0, new_dest_count / max(events_count, 1.0))

    rt_indices = sorted(set(rt_by_ep.get(ep_id, [])))

    row: Dict[str, Any] = {
        "episode_id": ep_id,
        "start_time": start_time,
        "end_time": end_time,
        "duration": duration,
        "source": ep.get("source", ""),
        "user": ep.get("user", ""),
        "candidate_gate": ep.get("candidate_gate", "UNKNOWN"),
        "legacy_sria_score": safe_float(ep.get("score")),
        "legacy_raw_score": safe_float(ep.get("raw_score"), safe_float(ep.get("score"))),
        "entropy_penalty": safe_float(ep.get("entropy_penalty")),
        "max_risk": safe_float(ep.get("max_risk")),
        "events_count": events_count,
        "destination_count": dest_count,
        "user_count": safe_float(ep.get("user_count"), 1.0 if ep.get("user") else 0.0),
        "new_destination_event_count": new_dest_count,
        "first_time_event_count": first_time_event_count,
        "first_time_signal_hits": first_time_signal_hits,
        "novelty_ratio": novelty_ratio,
        "compactness_score": safe_float(ep.get("compactness_score")),
        "fanout_velocity_score": safe_float(ep.get("fanout_velocity_score")),
        "peak_velocity_new_dests": safe_float(ep.get("peak_velocity_new_dests")),
        "signals": ";".join(sorted(sigset)),
        "label": 1 if ep_id in match_by_ep else 0,
        "redteam_indices": ";".join(str(i) for i in rt_indices),
        "redteam_count": len(rt_indices),
        "exact_start_count": exact_by_ep.get(ep_id, 0),
    }

    for s in signal_names:
        row[f"sig__{s}"] = 1.0 if s in sigset else 0.0

    return row


def load_rows(
    accepted_jsonl: Path,
    matches_jsonl: Optional[Path],
    signal_names: Sequence[str],
) -> List[Dict[str, Any]]:
    match_by_ep, rt_by_ep, exact_by_ep = load_match_maps(matches_jsonl)
    rows: List[Dict[str, Any]] = []
    print(f"Loading accepted episodes from {accepted_jsonl}...")
    for i, obj in enumerate(load_jsonl(accepted_jsonl), 1):
        if i % 100000 == 0:
            print(f"  loaded {i:,} accepted episodes...")
        rows.append(row_from_episode(obj, match_by_ep, rt_by_ep, exact_by_ep, signal_names))
    print(f"Loaded accepted rows: {len(rows):,}")
    return rows


def matrix_from_rows(rows: Sequence[Dict[str, Any]], feature_names: Sequence[str]) -> np.ndarray:
    X = np.zeros((len(rows), len(feature_names)), dtype=np.float32)
    for i, r in enumerate(rows):
        for j, n in enumerate(feature_names):
            X[i, j] = safe_float(r.get(n))
    return X


def model_scores(model: Any, X: np.ndarray) -> np.ndarray:
    if hasattr(model, "predict_proba"):
        proba = model.predict_proba(X)
        if proba.shape[1] == 2:
            return proba[:, 1]
        return proba[:, -1]
    if hasattr(model, "decision_function"):
        z = model.decision_function(X)
        z = np.asarray(z, dtype=np.float64)
        return 1.0 / (1.0 + np.exp(-np.clip(z, -50, 50)))
    pred = model.predict(X)
    return np.asarray(pred, dtype=np.float64)


def unpack_model_artifact(path: Path) -> Tuple[Any, List[str], Dict[str, Any]]:
    artifact = joblib.load(path)
    if isinstance(artifact, dict) and "model" in artifact:
        model = artifact["model"]
        feature_names = list(artifact.get("feature_names") or [])
        meta = {k: v for k, v in artifact.items() if k not in {"model"}}
    else:
        model = artifact
        feature_names = []
        meta = {"artifact_format": "raw_model_no_feature_names"}

    if not feature_names:
        raise ValueError(
            "Model artifact does not contain feature_names. Re-export with the SRIA RT v0.4.x/v0.5.x artifact format."
        )
    return model, feature_names, meta


def severity_from_score(score: float) -> str:
    if score >= 0.90:
        return "critical_review"
    if score >= 0.75:
        return "high_review"
    if score >= 0.50:
        return "medium_review"
    if score >= 0.25:
        return "low_review"
    return "background"


def priority_from_rank(rank: int) -> str:
    if rank <= 100:
        return "P1_top100"
    if rank <= 500:
        return "P2_top500"
    if rank <= 1000:
        return "P3_top1000"
    if rank <= 5000:
        return "P4_top5000"
    return "P5_long_tail"


def explanation_short(row: Dict[str, Any]) -> str:
    parts = []
    sigs = set(normalize_signals(row.get("signals")))
    if "first_time_source_user_to_dest" in sigs:
        parts.append("first-time source-user-destination edge")
    elif "first_time_user_to_dest" in sigs or "first_time_source_to_dest" in sigs:
        parts.append("first-time authentication edge")
    if "fanout_velocity" in sigs:
        parts.append("fanout velocity")
    if "compact_lateral_burst" in sigs:
        parts.append("compact lateral burst")
    if "propagation_convergence_bonus" in sigs:
        parts.append("propagation convergence")
    if not parts:
        parts.append("authentication topology anomaly")
    gate = str(row.get("candidate_gate") or "UNKNOWN")
    return f"{'; '.join(parts)}; gate={gate}"


def deployment_row(row: Dict[str, Any], rank: int, score: float) -> Dict[str, Any]:
    out = {k: row.get(k, "") for k in DEPLOYMENT_CSV_FIELDS if k not in {"rank", "sria_rt_model_score", "severity", "review_priority", "explanation_short"}}
    out["rank"] = rank
    out["sria_rt_model_score"] = float(score)
    out["severity"] = severity_from_score(float(score))
    out["review_priority"] = priority_from_rank(rank)
    out["explanation_short"] = explanation_short(row)
    return out


def research_row(row: Dict[str, Any], rank: int, score: float) -> Dict[str, Any]:
    out = deployment_row(row, rank, score)
    for k in RESEARCH_EXTRA_FIELDS:
        out[k] = row.get(k, "")
    return out


def write_csv(path: Path, rows: Sequence[Dict[str, Any]], fields: Sequence[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(fields), extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow(r)


def write_jsonl(path: Path, rows: Sequence[Dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, sort_keys=True) + "\n")


def topk_research_stats(ranked_rows: Sequence[Tuple[int, Dict[str, Any], float]], queue_sizes: Sequence[int]) -> Dict[int, Dict[str, Any]]:
    total_rt = len({int(x) for _, r, _ in ranked_rows for x in str(r.get("redteam_indices", "")).split(";") if x.strip().isdigit()})
    out: Dict[int, Dict[str, Any]] = {}
    for k in queue_sizes:
        rt = set()
        pos_eps = 0
        exact = 0
        gates = Counter()
        for _, r, _ in ranked_rows[:k]:
            if safe_int(r.get("label")) == 1:
                pos_eps += 1
            exact += safe_int(r.get("exact_start_count"))
            gates[str(r.get("candidate_gate", "UNKNOWN"))] += 1
            for x in str(r.get("redteam_indices", "")).split(";"):
                if x.strip().isdigit():
                    rt.add(int(x))
        kk = min(k, len(ranked_rows))
        out[k] = {
            "k": kk,
            "positive_episodes": pos_eps,
            "episode_precision": pos_eps / kk if kk else 0.0,
            "redteam_events": len(rt),
            "redteam_recall": len(rt) / total_rt if total_rt else 0.0,
            "exact_start_count": exact,
            "top_gates": gates.most_common(10),
        }
    return out


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="SRIA RT v0.5.1 deployment-style output separation")
    p.add_argument("--accepted-jsonl", required=True, help="Accepted episode JSONL to score")
    p.add_argument("--model-artifact", required=True, help="Joblib model artifact with model + feature_names")
    p.add_argument("--out-dir", required=True, help="Output directory")
    p.add_argument("--queue-sizes", default="100,500,1000,5000", help="Comma-separated queue sizes")
    p.add_argument("--matches-jsonl", default="", help="Optional redteam matches JSONL for research/debug validation only")
    p.add_argument("--write-research-debug", action="store_true", help="Write validation-bearing research/debug outputs")
    p.add_argument("--all-ranked-csv", action="store_true", help="Also write all ranked deployment rows to CSV")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    accepted_jsonl = Path(args.accepted_jsonl)
    model_artifact = Path(args.model_artifact)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    queue_sizes = [int(x) for x in args.queue_sizes.split(",") if x.strip()]
    max_queue = max(queue_sizes) if queue_sizes else 5000
    matches_jsonl = Path(args.matches_jsonl) if args.matches_jsonl else None

    print("=" * 80)
    print("SRIA RT v0.5.1 - Deployment-Style Output Separation")
    print("=" * 80)
    print(f"Accepted episodes: {accepted_jsonl}")
    print(f"Model artifact: {model_artifact}")
    print(f"Output dir: {out_dir}")
    print(f"Queue sizes: {queue_sizes}")
    print("NOTE: Deployment outputs exclude validation/redteam fields.")
    print("NOTE: Research/debug outputs are optional and must be explicitly requested.")
    print("=" * 80)

    t0 = time.time()
    model, feature_names, artifact_meta = unpack_model_artifact(model_artifact)
    signal_names = [n.replace("sig__", "") for n in feature_names if n.startswith("sig__")]
    if not signal_names:
        signal_names = list(DEFAULT_SIGNAL_NAMES)

    rows = load_rows(accepted_jsonl, matches_jsonl if args.write_research_debug else None, signal_names)
    X = matrix_from_rows(rows, feature_names)
    scores = model_scores(model, X)

    order = np.argsort(-np.asarray(scores))
    ranked: List[Tuple[int, Dict[str, Any], float]] = []
    for rank, idx in enumerate(order, 1):
        ranked.append((rank, rows[int(idx)], float(scores[int(idx)])))

    deploy_fields = DEPLOYMENT_CSV_FIELDS
    research_fields = DEPLOYMENT_CSV_FIELDS + RESEARCH_EXTRA_FIELDS

    for k in queue_sizes:
        selected = ranked[: min(k, len(ranked))]
        deployment_rows = [deployment_row(r, rank, score) for rank, r, score in selected]
        write_csv(out_dir / f"deployment_queue_top{k}.csv", deployment_rows, deploy_fields)
        write_jsonl(out_dir / f"deployment_queue_top{k}.jsonl", deployment_rows)

        if args.write_research_debug:
            debug_rows = [research_row(r, rank, score) for rank, r, score in selected]
            write_csv(out_dir / f"research_debug_queue_top{k}.csv", debug_rows, research_fields)
            write_jsonl(out_dir / f"research_debug_queue_top{k}.jsonl", debug_rows)

    if args.all_ranked_csv:
        all_deploy_rows = [deployment_row(r, rank, score) for rank, r, score in ranked]
        write_csv(out_dir / "deployment_queue_all_ranked.csv", all_deploy_rows, deploy_fields)

    manifest = {
        "version": "v0.5.1",
        "purpose": "deployment_style_output_separation",
        "accepted_jsonl": str(accepted_jsonl),
        "model_artifact": str(model_artifact),
        "queue_sizes": queue_sizes,
        "rows_scored": len(rows),
        "feature_count": len(feature_names),
        "feature_names": feature_names,
        "artifact_meta": artifact_meta,
        "deployment_outputs_exclude_validation_fields": sorted(VALIDATION_FIELD_NAMES),
        "research_debug_written": bool(args.write_research_debug),
        "elapsed_seconds": round(time.time() - t0, 3),
    }

    if args.write_research_debug:
        manifest["research_debug_stats"] = topk_research_stats(ranked, queue_sizes)

    (out_dir / "v051_manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = []
    lines.append("SRIA RT v0.5.1 Deployment Output Separation")
    lines.append("=" * 80)
    lines.append(f"accepted_jsonl: {accepted_jsonl}")
    lines.append(f"model_artifact: {model_artifact}")
    lines.append(f"rows_scored: {len(rows):,}")
    lines.append(f"feature_count: {len(feature_names)}")
    lines.append("deployment_note: deployment outputs intentionally exclude redteam/label validation fields")
    lines.append(f"research_debug_written: {bool(args.write_research_debug)}")
    lines.append("")
    lines.append("Deployment outputs:")
    for k in queue_sizes:
        lines.append(f"  deployment_queue_top{k}.csv")
        lines.append(f"  deployment_queue_top{k}.jsonl")
    if args.all_ranked_csv:
        lines.append("  deployment_queue_all_ranked.csv")
    if args.write_research_debug:
        lines.append("")
        lines.append("Research/debug outputs:")
        for k in queue_sizes:
            lines.append(f"  research_debug_queue_top{k}.csv")
            lines.append(f"  research_debug_queue_top{k}.jsonl")
        lines.append("")
        lines.append("Research/debug top-K validation summary:")
        for k, s in topk_research_stats(ranked, queue_sizes).items():
            lines.append(
                f"  top{k}: pos_eps={s['positive_episodes']} "
                f"ep_prec={s['episode_precision']:.4f} "
                f"rt_events={s['redteam_events']} "
                f"rt_recall={s['redteam_recall']:.4f} "
                f"exact_start={s['exact_start_count']}"
            )
    lines.append("")
    lines.append("Manifest: v051_manifest.json")

    report_path = out_dir / "v051_output_separation_report.txt"
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"Wrote report: {report_path}")


if __name__ == "__main__":
    main()
